# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent
---
#- name: Download OPNsense XML sample config
#  get_url:
#    url: https://raw.githubusercontent.com/opnsense/core/master/src/etc/config.xml.sample
#    dest: /tmp/config.xml

- name: fetch
  tags:
    - always
  include_tasks:
    file: fetch.yml
    apply:
      tags: fetch

- name: dnsserver
  tags:
    - always
  include_tasks:
    file: dnsserver.yml
    apply:
      tags: dnsserver

- name: user
  tags:
    - always
  include_tasks:
    file: user.yml
    apply:
      tags: user
  
- name: group
  tags:
    - always
  include_tasks:
    file: group.yml
    apply:
      tags: group

- name: general
  tags:
    - always
  include_tasks:
    file: general.yml
    apply:
      tags: general

#- name: sysctl
#  tags:
#    - always
#  include_tasks:
#    file: sysctl.yml
#    apply:
#      tags: sysctl

- name: authservers
  tags:
    - always
  include_tasks:
    file: authservers.yml
    apply:
      tags: authservers

- name: CAs
  tags:
    - always
  include_tasks:
    file: ca.yml
    apply:
      tags: ca

- name: VPN
  tags:
    - always
  include_tasks:
    file: vpn.yml
    apply:
      tags:
        - openvpn
        - vpn

- name: IPSec
  tags:
    - always
  include_tasks:
    file: ipsec.yml
    apply:
      tags:
        - vpn
        - ipsec

- name: interfaces
  tags:
    - always
  include_tasks:
    file: interfaces.yml
    apply:
      tags: interfaces

- name: vlans
  tags:
    - always
  include_tasks:
    file: vlans.yml
    apply:
      tags: vlans
  when: opn_interfaces_vlan_parent_interface is defined

- name: bridges
  tags:
    - always
  include_tasks:
    file: bridges.yml
    apply:
      tags: bridges
  
- name: virtualip
  tags:
    - always
  include_tasks:
    file: virtualip.yml
    apply:
      tags: virtualip

- name: alias
  tags:
    - always
  include_tasks:
    file: alias.yml
    apply:
      tags: alias

- name: filter
  tags:
    - always
  include_tasks:
    file: filter.yml
    apply:
      tags: filter
  
- name: gateways
  tags:
    - always
  include_tasks:
    file: gateways.yml
    apply:
      tags: gateways 
  #when: prod | default([])

- name: hasync
  tags:
    - always
  include_tasks:
    file: hasync.yml
    apply:
      tags: hasync

- name: dhcpd
  tags:
    - always
  include_tasks:
    file: dhcpd.yml
    apply:
      tags: dhcpd

- name: unbound
  tags:
    - always
  include_tasks:
    file: unbound.yml
    apply:
      tags: unbound

- name: syslog
  tags:
    - always
  include_tasks:
    file: syslog.yml
    apply:
      tags: syslog

- name: staticroutes
  tags:
    - always
  include_tasks:
    file: staticroutes.yml
    apply:
      tags: staticroutes

- name: nat
  tags:
    - always
  include_tasks:
    file: nat.yml
    apply:
      tags: nat

- name: laggs
  tags:
    - always
  include_tasks:
    file: laggs.yml
    apply:
      tags: laggs

- name: trim EOF
  delegate_to: localhost
  lineinfile:
    state: absent
    insertafter: EOF
    line: ""
    path: "{{ local_config_path }}"
  changed_when: false
  tags: trim

- name: fix xml start tag
  delegate_to: localhost
  lineinfile:
    line: '<?xml version="1.0"?>'
    regexp: '^<\?xml.*>'
    insertbefore: BOF
    path: "{{ local_config_path }}"
  changed_when: false
  tags: trim

- name: copy
  copy:
    src: "{{ local_config_path }}"
    dest: "{{ config_path }}"
    backup: yes
  register: config
  tags: copy

- name: clean,safe delete
  delegate_to: localhost
  shell: srm "{{ local_config_path }}"
  tags: clean

- name: reload
  command: "{{ item }}"
  with_items:
    - configctl filter sync
    - configctl service reload all
    - configctl webgui restart
  when: config.changed
  tags: reload
...
