---

- name: wireguard servers settings
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/OPNsense/wireguard/server/servers/server[@uuid='{{ uuid }}']/{{ item.key }}"
    value: "{{ item.value }}"
    pretty_print: true
  when:
    - item.key not in ['tunneladdress', 'peers'] or item.value is string
  with_dict:
    - "{{ serverscfg | default({}) }}"

- name: wireguard servers settings with list elements
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/OPNsense/wireguard/server/servers/server[@uuid='{{ uuid }}']/{{ item.key }}"
    value: "{{ item.value | join(',') }}"
    pretty_print: true
  when:
    - item.key in ['tunneladdress', 'peers'] and not item.value is string
  with_dict:
    - "{{ serverscfg | default({}) }}"

...
